[package]
name = "greenie"
version = "0.1.0"
authors = ["playx"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro=true

[dependencies]
syn = {version = "1", features=["full","fold"]}
quote = "1"